Kita akan membuat model sentiment classification model untuk membedakan antara review positif dan negatif. 

# Download Dataset

In [ ]:
import tensorflow_datasets as tfds

# load the imdb review dataset
imdb, info = tfds.load("imdb_reviews", with_info=True, as_supervised=True)

Dl Completed...: 0 url [00:00, ? url/s]

Dl Size...: 0 MiB [00:00, ? MiB/s]

0 examples [00:00, ? examples/s]

Shuffling and writing examples to /root/tensorflow_datasets/imdb_reviews/plain_text/1.0.0.incompleteQTVALG/imdb_reviews-train.tfrecord


  0%|          | 0/25000 [00:00<?, ? examples/s]

0 examples [00:00, ? examples/s]

Shuffling and writing examples to /root/tensorflow_datasets/imdb_reviews/plain_text/1.0.0.incompleteQTVALG/imdb_reviews-test.tfrecord


  0%|          | 0/25000 [00:00<?, ? examples/s]

0 examples [00:00, ? examples/s]

Shuffling and writing examples to /root/tensorflow_datasets/imdb_reviews/plain_text/1.0.0.incompleteQTVALG/imdb_reviews-unsupervised.tfrecord


  0%|          | 0/50000 [00:00<?, ? examples/s]

Dataset imdb_reviews downloaded and prepared to /root/tensorflow_datasets/imdb_reviews/plain_text/1.0.0. Subsequent calls will reuse this data.


In [ ]:
# information about dataset
print(info)

tfds.core.DatasetInfo(
    name='imdb_reviews',
    version=1.0.0,
    description='Large Movie Review Dataset.
This is a dataset for binary sentiment classification containing substantially more data than previous benchmark datasets. We provide a set of 25,000 highly polar movie reviews for training, and 25,000 for testing. There is additional unlabeled data for use as well.',
    homepage='http://ai.stanford.edu/~amaas/data/sentiment/',
    features=FeaturesDict({
        'label': ClassLabel(shape=(), dtype=tf.int64, num_classes=2),
        'text': Text(shape=(), dtype=tf.string),
    }),
    total_num_examples=100000,
    splits={
        'test': 25000,
        'train': 25000,
        'unsupervised': 50000,
    },
    supervised_keys=('text', 'label'),
    citation="""@InProceedings{maas-EtAl:2011:ACL-HLT2011,
      author    = {Maas, Andrew L.  and  Daly, Raymond E.  and  Pham, Peter T.  and  Huang, Dan  and  Ng, Andrew Y.  and  Potts, Christopher},
      title     = {Learning Word

Seperti yang kita lihat, ada total 100,000 contoh dalam dataset yang dipisah menjadi `train`, `test`, dan `unsupervised` set. Untuk lab ini, kita hanya akan menggunakan `train` dan `test` set karena kita akan membutuhkan contoh yang dilabeli untuk melatih model.

# Split the Dataset

Jika kita print `imdb`, kita akan melihat isinya berupa dictionary yang menunjuk pada objek `tf.data.Dataset`. Kita meneksplorasi lebih jauh untuk class dan API ini pada Course 4 nanti. Untuk sekarang, kita hanya perlu berfikir bahwa ini hanyalah sekedar contoh

In [ ]:
# print contents dataset
print(imdb)

{'test': <PrefetchDataset element_spec=(TensorSpec(shape=(), dtype=tf.string, name=None), TensorSpec(shape=(), dtype=tf.int64, name=None))>, 'train': <PrefetchDataset element_spec=(TensorSpec(shape=(), dtype=tf.string, name=None), TensorSpec(shape=(), dtype=tf.int64, name=None))>, 'unsupervised': <PrefetchDataset element_spec=(TensorSpec(shape=(), dtype=tf.string, name=None), TensorSpec(shape=(), dtype=tf.int64, name=None))>}


In [ ]:
# take 2 training examples and prin its contents
for example in imdb['train'].take(2):
  print(example)

(<tf.Tensor: shape=(), dtype=string, numpy=b"This was an absolutely terrible movie. Don't be lured in by Christopher Walken or Michael Ironside. Both are great actors, but this must simply be their worst role in history. Even their great acting could not redeem this movie's ridiculous storyline. This movie is an early nineties US propaganda piece. The most pathetic scenes were those when the Columbian rebels were making their cases for revolutions. Maria Conchita Alonso appeared phony, and her pseudo-love affair with Walken was nothing but a pathetic emotional plug in a movie that was devoid of any real meaning. I am disappointed that there are movies like this, ruining actor's like Christopher Walken's good name. I could barely sit through it.">, <tf.Tensor: shape=(), dtype=int64, numpy=0>)
(<tf.Tensor: shape=(), dtype=string, numpy=b'I have been known to fall asleep during films, but this is usually due to a combination of things including, really tired, being warm and comfortable on

In [ ]:
import numpy as np

# get the train and test
train_data, test_data = imdb['train'], imdb['test']

# inisiasi kalimat dan list label
training_sentences = []
training_labels = []

testing_sentences = []
testing_labels = []

# loop over all training example and save the sentences and labels
for s, l in train_data:
  training_sentences.append(s.numpy().decode('utf8'))
  training_labels.append(l.numpy())

# loop over all test examples and save the sentences and labels
for s, l in test_data:
  testing_sentences.append(s.numpy().decode('utf8'))
  testing_labels.append(l.numpy())

# convert labels lists to numpy array
training_labels_final = np.array(training_labels)
testing_labels_final = np.array(testing_labels)

# Generate Padded Sequences

Kita akan tokenize dan pad kalimat menjadi panjang yang seragam. Kita telah memisahkan parameter menjadi kode nya tersendiri sehingga bisa lebih mudah untuk mengubahnya jika kita ingin.

In [ ]:
# parameter
vocab_size = 10000
max_length = 120
embedding_dim = 16
trunc_type = 'post'
oov_tok = "<OOV>"

In [ ]:
from tensorflow.keras.preprocessing.text import Tokenizer
from tensorflow.keras.preprocessing.sequence import pad_sequences

# inisiasi class tokenizer
tokenizer = Tokenizer(num_words = vocab_size, oov_token = oov_tok)

# generate the word index dictionary for the training sentences
tokenizer.fit_on_texts(training_sentences)
word_index = tokenizer.word_index

# generate and pad the training sequences
sequences = tokenizer.texts_to_sequences(training_sentences)
padded = pad_sequences(sequences, maxlen=max_length, truncating=trunc_type)

# generate and pad the test sequences
testing_sequences = tokenizer.texts_to_sequences(testing_sentences)
testing_padded = pad_sequences(testing_sequences, maxlen=max_length)

# Build and Compile the Model

In [ ]:
import tensorflow as tf

In [ ]:
# model
model = tf.keras.Sequential([
      tf.keras.layers.Embedding(vocab_size, embedding_dim, input_length=max_length),
      tf.keras.layers.Flatten(),
      tf.keras.layers.Dense(6, activation='relu'),
      tf.keras.layers.Dense(1, activation='sigmoid')
])

# setup training parameters
model.compile(loss='binary_crossentropy', 
              optimizer='adam', 
              metrics=['accuracy']
)

# summary
model.summary()

Model: "sequential"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 embedding (Embedding)       (None, 120, 16)           160000    
                                                                 
 flatten (Flatten)           (None, 1920)              0         
                                                                 
 dense (Dense)               (None, 6)                 11526     
                                                                 
 dense_1 (Dense)             (None, 1)                 7         
                                                                 
Total params: 171,533
Trainable params: 171,533
Non-trainable params: 0
_________________________________________________________________


# Train model

In [ ]:
num_epochs = 10

# train
model.fit(padded, training_labels_final, epochs=num_epochs, validation_data=(testing_padded, testing_labels_final))

Epoch 1/10
782/782 [==============================] - 6s 6ms/step - loss: 0.4989 - accuracy: 0.7354 - val_loss: 0.3405 - val_accuracy: 0.8513
Epoch 2/10
782/782 [==============================] - 5s 6ms/step - loss: 0.2470 - accuracy: 0.9034 - val_loss: 0.3630 - val_accuracy: 0.8421
Epoch 3/10
782/782 [==============================] - 5s 7ms/step - loss: 0.1045 - accuracy: 0.9720 - val_loss: 0.4328 - val_accuracy: 0.8314
Epoch 4/10
782/782 [==============================] - 5s 7ms/step - loss: 0.0291 - accuracy: 0.9957 - val_loss: 0.5257 - val_accuracy: 0.8240
Epoch 5/10
782/782 [==============================] - 6s 8ms/step - loss: 0.0072 - accuracy: 0.9995 - val_loss: 0.5935 - val_accuracy: 0.8243
Epoch 6/10
782/782 [==============================] - 5s 7ms/step - loss: 0.0025 - accuracy: 0.9998 - val_loss: 0.6403 - val_accuracy: 0.8259
Epoch 7/10
782/782 [==============================] - 5s 7ms/step - loss: 9.9438e-04 - accuracy: 1.0000 - val_loss: 0.6786 - val_accuracy: 0.8278
Ep

In [ ]:
# get the embedding layer from the model 
embedding_layer = model.layers[0]

# get the weights of the embedding layer
embedding_weights = embedding_layer.get_weights()[0]

# print the shape
print(embedding_weights.shape)

(10000, 16)


In [ ]:
# get the index word dictionary
reverse_word_index = tokenizer.index_word

In [ ]:
import io

# Open writeable files
out_v = io.open('vecs.tsv', 'w', encoding='utf-8')
out_m = io.open('meta.tsv', 'w', encoding='utf-8')

# Initialize the loop. Start counting at `1` because `0` is just for the padding
for word_num in range(1, vocab_size):

  # Get the word associated at the current index
  word_name = reverse_word_index[word_num]

  # Get the embedding weights associated with the current index
  word_embedding = embedding_weights[word_num]

  # Write the word name
  out_m.write(word_name + "\n")

  # Write the word embedding
  out_v.write('\t'.join([str(x) for x in word_embedding]) + "\n")

# Close the files
out_v.close()
out_m.close()

In [ ]:
# Import files utilities in Colab
try:
  from google.colab import files
except ImportError:
  pass

# Download the files
else:
  files.download('vecs.tsv')
  files.download('meta.tsv')

<IPython.core.display.Javascript object>

<IPython.core.display.Javascript object>

<IPython.core.display.Javascript object>

<IPython.core.display.Javascript object>